services:
  jenkins:
    build: .
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50010:50000"
    container_name: jenkins-lts
    volumes:
      - ./jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - ..:/workspace
    restart: unless-stopped

  test-runner:
    build:
      context: .
      dockerfile: test-runner.Dockerfile
    image: poc-selenium-test-runner:latest
    container_name: test-runner-builder
    # This service is just for building the image, not running it
    entrypoint: ["/bin/true"]
